version: "3.8"

services:
  db:
    container_name: ${HOST_NAME}_db
    image: alterway/mysql:${MYSQL_VERSION}
    command: --innodb_strict_mode=off --innodb_flush_log_at_trx_commit=2 --innodb_flush_method=O_DIRECT --transaction-isolation=READ-COMMITTED --sql_mode=
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      LOCALTIME: ${LOCALTIME:-Europe/Moscow}
    volumes:
      - "${PWD}/.docker/volume/db/:/var/lib/mysql/:delegated"
    ports:
      - "3306:3306"
